/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpgrafos;

import java.awt.Color;
import java.io.File;
import java.util.Collection;
import java.util.Scanner;

/**
 *
 * @author Gustavo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    private Scanner in;
    private String implementacao;
    private String busca;
    private int numeroVertices;
    private int raiz;
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbtLista = new javax.swing.JRadioButton();
        rbtMatriz = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbtProfundidade = new javax.swing.JRadioButton();
        rbtLargura = new javax.swing.JRadioButton();
        btnExecutarImplementacao = new javax.swing.JButton();
        btnExecutarBusca = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        cbxGrafo = new javax.swing.JComboBox<>();
        btnCarregaGrafo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtRaiz = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblRaiz = new javax.swing.JLabel();
        btnRaiz = new javax.swing.JButton();
        btnExecutar = new javax.swing.JButton();
        lblValidadeRaiz = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnKruskal = new javax.swing.JButton();
        btnPrim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Escolha a implementação desejada:");

        buttonGroup1.add(rbtLista);
        rbtLista.setText("Lista de Adjacência");
        rbtLista.setEnabled(false);

        buttonGroup1.add(rbtMatriz);
        rbtMatriz.setText("Matriz de Adjacência");
        rbtMatriz.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Selecione a busca desejada:");

        buttonGroup2.add(rbtProfundidade);
        rbtProfundidade.setText("Busca em Profundidade");
        rbtProfundidade.setEnabled(false);

        buttonGroup2.add(rbtLargura);
        rbtLargura.setText("Busca em Largura");
        rbtLargura.setEnabled(false);

        btnExecutarImplementacao.setText("Ok");
        btnExecutarImplementacao.setEnabled(false);
        btnExecutarImplementacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarImplementacaoActionPerformed(evt);
            }
        });

        btnExecutarBusca.setText("Ok");
        btnExecutarBusca.setEnabled(false);
        btnExecutarBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarBuscaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Escolha o arquivo de texto representando o grafo desejado:");

        cbxGrafo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grafo1.txt", "grafo2.txt", "instancia_001.txt", "instancia_002.txt", "instancia_003.txt", "instancia_004.txt" }));

        btnCarregaGrafo.setText("Carregar");
        btnCarregaGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregaGrafoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Informe o vértice raiz:");

        txtRaiz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblRaiz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRaiz.setForeground(new java.awt.Color(255, 0, 0));
        lblRaiz.setText("Nenhum grafo foi carregado até o momento");

        btnRaiz.setText("OK");
        btnRaiz.setEnabled(false);
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnExecutar.setText("Executar");
        btnExecutar.setEnabled(false);
        btnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarActionPerformed(evt);
            }
        });

        lblValidadeRaiz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnKruskal.setText("Executar Kruskal");
        btnKruskal.setEnabled(false);
        btnKruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKruskalActionPerformed(evt);
            }
        });

        btnPrim.setText("Executar Prim");
        btnPrim.setEnabled(false);
        btnPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtLista)
                                .addGap(18, 18, 18)
                                .addComponent(rbtMatriz)
                                .addGap(18, 18, 18)
                                .addComponent(btnExecutarImplementacao))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(txtRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(lblValidadeRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtProfundidade)
                        .addGap(18, 18, 18)
                        .addComponent(rbtLargura)
                        .addGap(18, 18, 18)
                        .addComponent(btnExecutarBusca)
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKruskal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrim, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbxGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(btnCarregaGrafo))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(btnExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCarregaGrafo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtMatriz)
                        .addComponent(rbtLista)
                        .addComponent(btnExecutarImplementacao)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(lblValidadeRaiz)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRaiz))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtProfundidade)
                    .addComponent(rbtLargura)
                    .addComponent(btnExecutarBusca)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblRaiz)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKruskal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExecutarImplementacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarImplementacaoActionPerformed
        // TODO add your handling code here:
        if(this.rbtLista.isSelected()){
            this.implementacao = this.rbtLista.getText();
        }else if(this.rbtMatriz.isSelected()){
            this.implementacao = this.rbtMatriz.getText();
        }else{
            System.out.println("Selecione uma das implementações");
            return;
        }
        rbtProfundidade.setEnabled(true);
        rbtLargura.setEnabled(true);
        btnExecutarBusca.setEnabled(true);
        this.btnKruskal.setEnabled(true);
        this.btnPrim.setEnabled(true);
    }//GEN-LAST:event_btnExecutarImplementacaoActionPerformed

    private void btnCarregaGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregaGrafoActionPerformed
        // TODO add your handling code here:
        try{
            this.in = new Scanner(new File((String) this.cbxGrafo.getSelectedItem()));
            this.numeroVertices = Integer.parseInt(in.nextLine());
            this.lblRaiz.setText("O grafo carregado possui vérties de 0 a " + (this.numeroVertices-1));
            this.lblRaiz.setForeground(Color.blue);
            this.btnExecutarImplementacao.setEnabled(true);
            this.rbtLista.setEnabled(true);
            this.rbtMatriz.setEnabled(true);
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnCarregaGrafoActionPerformed

    private void btnExecutarBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarBuscaActionPerformed
        // TODO add your handling code here:
        if(this.rbtLargura.isSelected()){
            this.busca = this.rbtLargura.getText();
        }else if(this.rbtProfundidade.isSelected()){
            this.busca = this.rbtProfundidade.getText();
        }else{
            System.out.println("Selecione uma das buscas!");
            return;
        }
        this.btnRaiz.setEnabled(true);
    }//GEN-LAST:event_btnExecutarBuscaActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        // TODO add your handling code here:
        try{
            this.raiz = Integer.parseInt(this.txtRaiz.getText());
            if(!(this.raiz >= 0 && this.raiz <= this.numeroVertices-1)){
                System.out.println("Por favor, informe um vértice entre os existentes no grafo");
                this.lblValidadeRaiz.setText("Inválido!");
                this.lblValidadeRaiz.setForeground(Color.red);
                this.btnExecutar.setEnabled(false);
            }else{
                this.lblValidadeRaiz.setText("Válido!");
                this.lblValidadeRaiz.setForeground(Color.green);
                this.btnExecutar.setEnabled(true);
            }
        }catch(Exception ex){
            System.out.println("Bitch, please! Just numbers");
            this.lblValidadeRaiz.setText("Inválido!");
            this.lblValidadeRaiz.setForeground(Color.red);
            this.btnExecutar.setEnabled(false);
        }       
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        // TODO add your handling code here:
        this.txtResultado.setText("");
        String texto = "";
        TpGrafos tp = new TpGrafos(this.in, this.implementacao, this.numeroVertices, this.busca, this.raiz);
        /*if("Busca em Profundidade".equals(this.busca)){
            texto += tp.arestasDeRetorno() + "\n";
            texto += tp.arestasDeAvanco() + "\n";
            texto += tp.arestasDeArvore() + "\n";
            texto += tp.arestasDeCruzamento() + "\n";
            texto += tp.existeCiclo();
            this.txtResultado.setText(texto);
        }else{
            this.txtResultado.setText(tp.paisEDistancias());
        }*/
        zeraTudo();
    }//GEN-LAST:event_btnExecutarActionPerformed

    private void btnKruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKruskalActionPerformed
        // TODO add your handling code here:
        TpGrafos tp = new TpGrafos(this.in, this.implementacao, this.numeroVertices, "Kruskal");
 
    }//GEN-LAST:event_btnKruskalActionPerformed

    private void btnPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimActionPerformed
        // TODO add your handling code here:
        TpGrafos tp = new TpGrafos(this.in,this.implementacao,this.numeroVertices, "Prim");
    }//GEN-LAST:event_btnPrimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    private void zeraTudo(){
        this.in = null;
        this.rbtLargura.setEnabled(false);
        this.rbtLista.setEnabled(false);
        this.rbtProfundidade.setEnabled(false);
        this.rbtMatriz.setEnabled(false);
        this.btnExecutar.setEnabled(false);
        this.btnExecutarImplementacao.setEnabled(false);
        this.btnExecutarBusca.setEnabled(false);
        this.btnRaiz.setEnabled(false);
        this.busca = null;
        this.implementacao = null;
        this.numeroVertices = -1;
        this.raiz = -1;
        this.txtRaiz.setText("");
        this.lblValidadeRaiz.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregaGrafo;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JButton btnExecutarBusca;
    private javax.swing.JButton btnExecutarImplementacao;
    private javax.swing.JButton btnKruskal;
    private javax.swing.JButton btnPrim;
    private javax.swing.JButton btnRaiz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxGrafo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblRaiz;
    private javax.swing.JLabel lblValidadeRaiz;
    private javax.swing.JRadioButton rbtLargura;
    private javax.swing.JRadioButton rbtLista;
    private javax.swing.JRadioButton rbtMatriz;
    private javax.swing.JRadioButton rbtProfundidade;
    private javax.swing.JTextField txtRaiz;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
